version: "3.3"

services:
  thalos_web:
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true