version: "3.3"

services:
  web:
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/static
    ports:
      - "1337:80"
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: