version: "3.3"

services:
  thalos_web:
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - .:/code
      - static_volume_thalos:/root/www/ThalosCinemaSystem/staticfiles
      - media_volume_thalos:/root/www/ThalosCinemaSystem/mediafiles/upload_thumbnails
    expose:
      - "8004"
    networks:
      - nginx_network
volumes:
  static_volume_thalos:
    external: true
  media_volume_thalos:
    external: true

networks:
  nginx_network:
    external: true