version: "3.3"

services:
  thalos_web_1:
    container_name: thalos_web_1
    build: .
    command: daphne TCS.asgi:application -b 0.0.0.0 -p 8004
    volumes:
      - .:/code
    expose:
      - "8004"
    env_file:
      - ./.env.prod
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true