version: "3.3"

services:
  thalos_web:
    build: .
    command: gunicorn -w 1 TCS.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - .:/code
    expose:
      - "8004"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true