version: "3.3"

services:
  thalos_web:
    container_name: thalos_web_1
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - .:/code
    expose:
      - "8004"
    env_file:
      - ./.env.prod
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true