version: "3.3"

services:
  web:
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
  wronamichal_pl:
    restart: always
    build: ./nginx
    volumes:
      - .:/usr/share/nginx/html/