version: "3.3"

services:
  web:
    build: .
    command: gunicorn  --workers 2 TCS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: