version: "3.3"

services:
  thalos_web:
    build: .
    command: gunicorn TCS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true