# Generated by Django 4.0.3 on 2022-05-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='marathon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.marathon'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
