# Generated by Django 4.0.3 on 2022-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_marathon_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='movies_images'),
            preserve_default=False,
        ),
    ]
