# Generated by Django 4.0.3 on 2022-05-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_seat_is_durning_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='marathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.marathon'),
        ),
    ]
