# Generated by Django 4.0.3 on 2022-05-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_projection_is_cyclic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='projection',
            name='type_projection',
            field=models.CharField(choices=[('Lektor', 'Lektor'), ('Napisy', 'Napisy'), ('Dubbing', 'Dubbing')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='website.genre'),
        ),
        migrations.AddField(
            model_name='projection',
            name='is_cyclic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='marathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.marathon'),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_durning_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
