# Generated by Django 4.0.3 on 2022-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_genre_movie_movie_genre_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='upload_thumbnails'),
        ),
    ]
