name: Thalos Deploy via SSH to VPS server
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull new code and restart all services
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST_SSH }}
       username: ${{ secrets.USERNAME_SSH }}
       password: ${{ secrets.PASSWORD_SSH }}
       port: ${{ secrets.PORT_SSH }}
       script: | 
        sudo su - thalos -s /bin/bash
        sudo cd ThalosCinemaSystem/
        sudo git pull
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx